DROP TABLE IF EXISTS user_event;
DROP TABLE IF EXISTS contracts;
DROP TABLE IF EXISTS applications;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS admins;

CREATE TABLE admins
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login       VARCHAR(50)     NOT NULL    UNIQUE,
    password    VARCHAR(200)    NOT NULL,
    role        VARCHAR(10)     NOT NULL,
    name        VARCHAR(100)    NOT NULL
);

CREATE TABLE contracts
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signed      BOOLEAN         NOT NULL    DEFAULT FALSE,
    admin_id    INTEGER UNIQUE REFERENCES admins(id) ON DELETE CASCADE
);

CREATE TABLE applications
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id    INTEGER UNIQUE REFERENCES admins(id) ON DELETE CASCADE
);

CREATE TABLE users
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login       VARCHAR(50)     NOT NULL    UNIQUE,
    password    VARCHAR(200)    NOT NULL,
    role        VARCHAR(10)     NOT NULL,
    name        VARCHAR(100)    NOT NULL,
    age         INT             NOT NULL
);

CREATE TABLE events
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)    NOT NULL    UNIQUE,
    price       INT             NOT NULL,
    owner_id    INTEGER         NOT NULL,
    FOREIGN KEY (owner_id) REFERENCES admins (id) ON DELETE CASCADE
);

CREATE TABLE user_event
(
    user_id     INT REFERENCES users(id),
    event_id    INT REFERENCES events(id),
    PRIMARY KEY (user_id, event_id)
);